CREATE TABLE hotel (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  name VARCHAR (255) NOT NULL,
  city VARCHAR (255) NOT NULL,
  country VARCHAR (255) NOT NULL,
  rating INT NOT NULL,
  description TEXT NOT NULL
);

-- /Users/user/Documents/'Tom\'s React'/'New Projects'/'Stay With Us'/server/db/db.sql

insert into hotel (name, city, country, rating, description) values ('Spohn Hotel', 'Bearna', 'Ireland', 3, 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into hotel (name, city, country, rating, description) values ('Vidon Hotel', 'Kerkrade', 'Netherlands', 1, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into hotel (name, city, country, rating, description) values ('Florence Hotel', 'Marseille', 'France', 4, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into hotel (name, city, country, rating, description) values ('Dwight Hotel', 'Langley', 'United Kingdom', 4, 'Integer ac neque.');
insert into hotel (name, city, country, rating, description) values ('Summerview Hotel', 'Caen', 'France', 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into hotel (name, city, country, rating, description) values ('Laurel Hotel', 'Cabeço de Vide', 'Portugal', 2, 'In congue.');
insert into hotel (name, city, country, rating, description) values ('Dryden Hotel', 'Oughterard', 'Ireland', 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into hotel (name, city, country, rating, description) values ('Kropf Hotel', 'Oeiras', 'Portugal', 4, 'Mauris sit amet eros.');
insert into hotel (name, city, country, rating, description) values ('Ramsey Hotel', 'Clamart', 'France', 5, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into hotel (name, city, country, rating, description) values ('Sunfield Hotel', 'Saint-Maur-des-Fossés', 'France', 4, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into hotel (name, city, country, rating, description) values ('Coleman Hotel', 'Carvalhinho', 'Portugal', 1, 'Nulla suscipit ligula in lacus.');
insert into hotel (name, city, country, rating, description) values ('Knutson Hotel', 'Meirinhas', 'Portugal', 3, 'Praesent blandit.');
insert into hotel (name, city, country, rating, description) values ('Summerview Hotel', 'Heerlen', 'Netherlands', 1, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into hotel (name, city, country, rating, description) values ('Sunnyside Hotel', 'Nice', 'France', 1, 'Aenean lectus. Pellentesque eget nunc.');
insert into hotel (name, city, country, rating, description) values ('Golden Leaf Hotel', 'Quetigny', 'France', 4, 'Aenean auctor gravida sem.');
insert into hotel (name, city, country, rating, description) values ('Oriole Hotel', 'Noyon', 'France', 5, 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into hotel (name, city, country, rating, description) values ('Anniversary Hotel', 'Vittel', 'France', 3, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into hotel (name, city, country, rating, description) values ('Mccormick Hotel', 'Praia da Vitória', 'Portugal', 4, 'Nullam molestie nibh in lectus.');
insert into hotel (name, city, country, rating, description) values ('Quincy Hotel', 'Vale de Figueira', 'Portugal', 1, 'Nunc purus. Phasellus in felis.');
insert into hotel (name, city, country, rating, description) values ('Bowman Hotel', 'Tours', 'France', 1, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into hotel (name, city, country, rating, description) values ('Mcguire Hotel', 'Agrela', 'Portugal', 5, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into hotel (name, city, country, rating, description) values ('Harbort Hotel', 'Brest', 'France', 2, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into hotel (name, city, country, rating, description) values ('Washington Hotel', 'Moita da Roda', 'Portugal', 4, 'Donec semper sapien a libero.');
insert into hotel (name, city, country, rating, description) values ('Graedel Hotel', 'Nîmes', 'France', 3, 'Vivamus tortor.');
insert into hotel (name, city, country, rating, description) values ('Kingsford Hotel', 'Vale Maceiras', 'Portugal', 2, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into hotel (name, city, country, rating, description) values ('Talmadge Hotel', 'Vila Boa do Bispo', 'Portugal', 2, 'Nullam molestie nibh in lectus.');
insert into hotel (name, city, country, rating, description) values ('Atwood Hotel', 'Lameiras', 'Portugal', 3, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into hotel (name, city, country, rating, description) values ('Lindbergh Hotel', 'Lagny-sur-Marne', 'France', 4, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into hotel (name, city, country, rating, description) values ('Kingsford Hotel', 'Laspezia', 'Italy', 1, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into hotel (name, city, country, rating, description) values ('Service Hotel', 'Woippy', 'France', 1, 'In sagittis dui vel nisl.');
insert into hotel (name, city, country, rating, description) values ('Eagle Crest Hotel', 'Juvisy-sur-Orge', 'France', 2, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into hotel (name, city, country, rating, description) values ('Mitchell Hotel', 'Rouen', 'France', 2, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into hotel (name, city, country, rating, description) values ('Kings Hotel', 'Penhascoso', 'Portugal', 5, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into hotel (name, city, country, rating, description) values ('Division Hotel', 'Sangalhos', 'Portugal', 2, 'Nunc rhoncus dui vel sem.');
insert into hotel (name, city, country, rating, description) values ('Blackbird Hotel', 'Nuits-Saint-Georges', 'France', 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into hotel (name, city, country, rating, description) values ('Thompson Hotel', 'Rosais', 'Portugal', 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into hotel (name, city, country, rating, description) values ('Kensington Hotel', 'Belmullet', 'Ireland', 5, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into hotel (name, city, country, rating, description) values ('Petterle Hotel', 'Dortmund', 'Germany', 4, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into hotel (name, city, country, rating, description) values ('Kenwood Hotel', 'Palaiseau', 'France', 3, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into hotel (name, city, country, rating, description) values ('Walton Hotel', 'Fontenay-sous-Bois', 'France', 3, 'Nunc purus. Phasellus in felis.');
insert into hotel (name, city, country, rating, description) values ('Mendota Hotel', 'Toulouse', 'France', 1, 'Fusce consequat. Nulla nisl.');
insert into hotel (name, city, country, rating, description) values ('Thackeray Hotel', 'Carrasqueira', 'Portugal', 4, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into hotel (name, city, country, rating, description) values ('Kenwood Hotel', 'Reguenga', 'Portugal', 4, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into hotel (name, city, country, rating, description) values ('Charing Cross Hotel', 'Ballyjamesduff', 'Ireland', 5, 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into hotel (name, city, country, rating, description) values ('Forster Hotel', 'Thiers', 'France', 1, 'Proin eu mi. Nulla ac enim.');
insert into hotel (name, city, country, rating, description) values ('Brickson Park Hotel', 'Macedo de Cavaleiros', 'Portugal', 5, 'Ut tellus.');
insert into hotel (name, city, country, rating, description) values ('Village Green Hotel', 'Granard', 'Ireland', 3, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into hotel (name, city, country, rating, description) values ('Barby Hotel', 'London', 'United Kingdom', 4, 'Cras pellentesque volutpat dui.');
insert into hotel (name, city, country, rating, description) values ('Lakewood Hotel', 'Ballyboden', 'Ireland', 3, 'Quisque porta volutpat erat.');
insert into hotel (name, city, country, rating, description) values ('Dwight Hotel', 'Setúbal', 'Portugal', 4, 'Donec posuere metus vitae ipsum.');
insert into hotel (name, city, country, rating, description) values ('Elgar Hotel', 'Chã', 'Portugal', 1, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into hotel (name, city, country, rating, description) values ('Riverside Hotel', 'Guéret', 'France', 5, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into hotel (name, city, country, rating, description) values ('Shoshone Hotel', 'Cholet', 'France', 2, 'Fusce consequat. Nulla nisl.');
insert into hotel (name, city, country, rating, description) values ('Chive Hotel', 'Perpignan', 'France', 5, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into hotel (name, city, country, rating, description) values ('Raven Hotel', 'Quintães', 'Portugal', 1, 'Nulla tempus.');
insert into hotel (name, city, country, rating, description) values ('Nevada Hotel', 'Paris 13', 'France', 2, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into hotel (name, city, country, rating, description) values ('Crest Line Hotel', 'Barra Cheia', 'Portugal', 5, 'Sed accumsan felis.');
insert into hotel (name, city, country, rating, description) values ('Straubel Hotel', 'Youghal', 'Ireland', 2, 'Suspendisse potenti.');
insert into hotel (name, city, country, rating, description) values ('Tomscot Hotel', 'Hanau', 'Germany', 2, 'Mauris lacinia sapien quis libero.');
insert into hotel (name, city, country, rating, description) values ('West Hotel', 'Hamburg', 'Germany', 4, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into hotel (name, city, country, rating, description) values ('Superior Hotel', 'Cabanas de Viriato', 'Portugal', 1, 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into hotel (name, city, country, rating, description) values ('Hoepker Hotel', 'Carvoeira', 'Portugal', 5, 'Etiam faucibus cursus urna. Ut tellus.');
insert into hotel (name, city, country, rating, description) values ('Jay Hotel', 'Mosteiro', 'Portugal', 2, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into hotel (name, city, country, rating, description) values ('Havey Hotel', 'Coruña, A', 'Spain', 3, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into hotel (name, city, country, rating, description) values ('Talisman Hotel', 'Hamburg', 'Germany', 4, 'Cras non velit nec nisi vulputate nonummy.');
insert into hotel (name, city, country, rating, description) values ('Alpine Hotel', 'Granja', 'Portugal', 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into hotel (name, city, country, rating, description) values ('Corben Hotel', 'Armamar', 'Portugal', 2, 'In eleifend quam a odio.');
insert into hotel (name, city, country, rating, description) values ('Gina Hotel', 'Labruge', 'Portugal', 5, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into hotel (name, city, country, rating, description) values ('Westport Hotel', 'Fontinha', 'Portugal', 3, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into hotel (name, city, country, rating, description) values ('Clove Hotel', 'Casa Nova', 'Portugal', 5, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into hotel (name, city, country, rating, description) values ('Golf View Hotel', 'Vincennes', 'France', 3, 'Integer a nibh.');
insert into hotel (name, city, country, rating, description) values ('Grover Hotel', 'Dos Hermanas', 'Spain', 1, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into hotel (name, city, country, rating, description) values ('Packers Hotel', 'Lille', 'France', 4, 'Mauris sit amet eros.');
insert into hotel (name, city, country, rating, description) values ('Pearson Hotel', 'La Rochelle', 'France', 2, 'Nulla tellus.');
insert into hotel (name, city, country, rating, description) values ('Walton Hotel', 'Remscheid', 'Germany', 4, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into hotel (name, city, country, rating, description) values ('La Follette Hotel', 'Sande São Martinho', 'Portugal', 2, 'Etiam justo.');
insert into hotel (name, city, country, rating, description) values ('Fieldstone Hotel', 'Pego Longo', 'Portugal', 1, 'Nulla ac enim.');
insert into hotel (name, city, country, rating, description) values ('Saint Paul Hotel', 'Zürich', 'Switzerland', 5, 'Duis ac nibh.');
insert into hotel (name, city, country, rating, description) values ('Lunder Hotel', 'Annecy', 'France', 3, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into hotel (name, city, country, rating, description) values ('Upham Hotel', 'Vigo', 'Spain', 2, 'Nulla tempus.');
insert into hotel (name, city, country, rating, description) values ('Susan Hotel', 'Lamego', 'Portugal', 5, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into hotel (name, city, country, rating, description) values ('Ruskin Hotel', 'Saint-Jean-de-Monts', 'France', 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into hotel (name, city, country, rating, description) values ('Melvin Hotel', 'Bochum', 'Germany', 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into hotel (name, city, country, rating, description) values ('Veith Hotel', 'Gaillac', 'France', 4, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into hotel (name, city, country, rating, description) values ('Carey Hotel', 'Bremerhaven', 'Germany', 5, 'Suspendisse potenti. In eleifend quam a odio.');
insert into hotel (name, city, country, rating, description) values ('Declaration Hotel', 'Cartagena', 'Spain', 3, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into hotel (name, city, country, rating, description) values ('Brentwood Hotel', 'Suresnes', 'France', 3, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into hotel (name, city, country, rating, description) values ('Independence Hotel', 'Caldas da Rainha', 'Portugal', 2, 'Suspendisse potenti.');
insert into hotel (name, city, country, rating, description) values ('Bunker Hill Hotel', 'Feteira Grande', 'Portugal', 1, 'Nulla nisl.');
insert into hotel (name, city, country, rating, description) values ('Kropf Hotel', 'Palmas De Gran Canaria, Las', 'Spain', 4, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into hotel (name, city, country, rating, description) values ('Sunfield Hotel', 'Elx/Elche', 'Spain', 1, 'Integer non velit.');
insert into hotel (name, city, country, rating, description) values ('Calypso Hotel', 'Verona', 'Italy', 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into hotel (name, city, country, rating, description) values ('Kenwood Hotel', 'Marseille', 'France', 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into hotel (name, city, country, rating, description) values ('Westerfield Hotel', 'Hyères', 'France', 4, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into hotel (name, city, country, rating, description) values ('Roth Hotel', 'Naas', 'Ireland', 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into hotel (name, city, country, rating, description) values ('Granby Hotel', 'Paris 08', 'France', 2, 'Praesent blandit.');
insert into hotel (name, city, country, rating, description) values ('Golf Hotel', 'São Pedro de Trafaria', 'Portugal', 5, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into hotel (name, city, country, rating, description) values ('Clyde Gallagher Hotel', 'Rennes', 'France', 1, 'Suspendisse ornare consequat lectus.');
insert into hotel (name, city, country, rating, description) values ('Mifflin Hotel', 'Alvito', 'Portugal', 4, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into hotel (name, city, country, rating, description) values ('Haas Hotel', 'Caen', 'France', 4, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');


CREATE TABLE room (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  hotel_id BIGINT REFERENCES "hotel" NOT NULL,
  room_no INT NOT NULL,
  no_of_beds INT NOT NULL,
  price_per_night NUMERIC (12, 2) NOT NULL
);

insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (6, 189, 1, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 65, 2, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 91, 3, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (4, 217, 2, 97.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (82, 184, 4, 92.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 196, 1, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 174, 1, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (53, 70, 4, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (57, 63, 4, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (59, 41, 3, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (82, 216, 4, 30.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 92, 4, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (62, 136, 4, 90.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 167, 1, 29.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (93, 88, 2, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (14, 118, 2, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (96, 58, 3, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (60, 25, 4, 66.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (45, 101, 4, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (91, 167, 1, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 7, 4, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (59, 174, 1, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 48, 1, 27.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 18, 3, 36.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (28, 96, 1, 108.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 188, 4, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (83, 221, 2, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (20, 105, 4, 17.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (37, 54, 4, 24.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (50, 63, 3, 71.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (30, 109, 4, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (37, 30, 3, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (57, 239, 2, 50.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (7, 85, 2, 84.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (8, 62, 2, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 161, 2, 83.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (30, 62, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (48, 164, 3, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 22, 3, 88.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (26, 161, 2, 93.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 27, 4, 77.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 43, 1, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (4, 230, 2, 38.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 225, 2, 92.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (32, 243, 1, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 18, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 187, 2, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 39, 4, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (47, 28, 2, 62.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (94, 83, 1, 38.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (26, 57, 2, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (48, 241, 2, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (52, 236, 3, 86.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (97, 31, 3, 73.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (49, 201, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 10, 1, 37.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (57, 167, 3, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (80, 245, 2, 47.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 119, 1, 22.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (58, 137, 2, 110.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (69, 116, 3, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (74, 101, 4, 67.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (26, 131, 3, 43.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (70, 72, 4, 88.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 187, 1, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (45, 210, 4, 112.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (45, 63, 2, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (93, 158, 3, 113.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (92, 208, 2, 17.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (82, 117, 4, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 77, 1, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (51, 136, 4, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (64, 102, 4, 103.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (65, 250, 2, 40.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (33, 21, 2, 37.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (50, 25, 2, 81.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (80, 130, 4, 36.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 215, 3, 108.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 41, 3, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 217, 1, 37.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (71, 119, 2, 84.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 217, 2, 105.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 125, 2, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 191, 4, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (81, 234, 4, 20.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 126, 1, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (8, 186, 1, 84.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 132, 3, 19.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 24, 4, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (28, 224, 4, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 49, 1, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (50, 9, 3, 81.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (83, 185, 1, 42.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (72, 95, 4, 36.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (55, 144, 2, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (89, 244, 3, 49.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 62, 1, 93.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 106, 2, 43.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 24, 3, 64.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (4, 122, 4, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (34, 236, 1, 88.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (22, 32, 4, 73.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 82, 3, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (59, 164, 4, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (90, 206, 1, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (95, 141, 1, 109.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (50, 233, 1, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 73, 2, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 156, 2, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (11, 45, 1, 90.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (58, 32, 1, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (95, 101, 1, 64.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (77, 17, 4, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 133, 4, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (57, 196, 1, 93.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 193, 3, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 145, 3, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 195, 1, 86.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (57, 41, 2, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 22, 4, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (8, 131, 3, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (76, 190, 3, 81.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (34, 108, 3, 91.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (92, 150, 4, 29.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (58, 126, 2, 109.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (77, 142, 4, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (60, 83, 2, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (79, 216, 3, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (52, 217, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 213, 3, 102.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (58, 248, 1, 79.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 207, 3, 103.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 175, 2, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 178, 4, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (74, 162, 2, 108.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 114, 1, 39.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 8, 1, 113.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (96, 196, 2, 105.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (67, 168, 2, 99.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (47, 151, 4, 63.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (15, 49, 1, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (89, 216, 4, 102.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 60, 4, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (46, 192, 3, 54.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 203, 2, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 156, 3, 112.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 118, 2, 105.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (39, 152, 3, 98.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (52, 40, 3, 57.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 28, 1, 110.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (27, 31, 1, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (52, 77, 1, 46.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (62, 69, 3, 51.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 104, 1, 49.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 136, 4, 46.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 43, 4, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 161, 2, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (13, 103, 1, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 6, 2, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (11, 210, 2, 91.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 11, 2, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 7, 4, 101.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 36, 1, 22.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (36, 180, 2, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 63, 2, 63.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 151, 1, 112.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (93, 93, 2, 34.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (45, 140, 1, 84.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (75, 236, 4, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (75, 47, 3, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 39, 4, 104.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 194, 3, 59.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 246, 1, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 91, 2, 45.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (13, 187, 1, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 227, 1, 90.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 128, 4, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (41, 14, 4, 91.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 104, 2, 83.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (81, 185, 2, 64.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (97, 159, 4, 97.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (92, 137, 1, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (16, 185, 2, 41.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (69, 157, 2, 45.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (5, 138, 4, 32.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 102, 4, 53.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (47, 200, 3, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 209, 2, 19.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (48, 219, 1, 19.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 27, 1, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (51, 117, 1, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (16, 159, 1, 54.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (16, 15, 4, 24.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 159, 1, 89.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 89, 4, 79.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (70, 47, 3, 91.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (34, 211, 4, 27.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 231, 4, 103.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 190, 3, 15.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (67, 31, 3, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (5, 162, 1, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 120, 3, 31.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 217, 4, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (33, 57, 2, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (79, 178, 2, 113.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (16, 24, 4, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 91, 4, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 59, 3, 83.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (36, 107, 1, 99.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (41, 242, 2, 99.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 144, 2, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (84, 43, 4, 59.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (11, 176, 4, 59.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 16, 1, 40.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (79, 195, 4, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (20, 28, 4, 49.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (15, 203, 4, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (78, 92, 4, 78.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (95, 120, 1, 45.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (97, 115, 1, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 180, 1, 104.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (74, 160, 2, 61.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 131, 4, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (3, 148, 4, 99.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 76, 4, 71.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (43, 50, 1, 40.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 88, 2, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (16, 250, 2, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (14, 162, 1, 97.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 116, 3, 46.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (76, 72, 2, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (78, 57, 3, 109.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (22, 55, 3, 77.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 99, 2, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (90, 229, 3, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (53, 80, 4, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (51, 149, 3, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 27, 2, 81.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 37, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 104, 1, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (15, 130, 3, 59.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (48, 198, 3, 84.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 116, 2, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 116, 3, 92.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (24, 25, 4, 61.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (39, 246, 4, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 131, 1, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (43, 5, 4, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 224, 4, 86.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (93, 180, 3, 21.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (71, 214, 3, 69.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (25, 227, 3, 15.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (91, 34, 2, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (95, 137, 3, 89.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (3, 247, 3, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (47, 157, 2, 108.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 130, 2, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (31, 91, 2, 23.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (22, 192, 4, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (96, 164, 4, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (84, 1, 3, 40.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (72, 165, 1, 85.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (20, 192, 3, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 73, 2, 46.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (15, 157, 2, 34.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 111, 4, 89.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 238, 2, 98.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 123, 1, 15.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (77, 189, 1, 24.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (49, 2, 2, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 175, 4, 73.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 235, 1, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (7, 180, 3, 104.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (76, 132, 3, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (43, 157, 1, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 122, 4, 67.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 156, 2, 34.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (75, 3, 3, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (23, 240, 1, 84.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (30, 156, 4, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (14, 106, 3, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (90, 183, 1, 41.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (31, 10, 4, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (32, 26, 2, 73.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (47, 90, 1, 90.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (71, 188, 1, 113.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 14, 1, 61.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (28, 6, 2, 75.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 47, 3, 34.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (4, 150, 2, 103.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (69, 152, 4, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (29, 114, 4, 23.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (55, 119, 1, 110.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (37, 225, 3, 31.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (39, 106, 1, 30.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 47, 4, 51.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 95, 1, 20.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (24, 70, 4, 62.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (49, 232, 1, 39.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 96, 4, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (95, 185, 2, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (51, 90, 2, 93.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (36, 220, 2, 51.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (52, 18, 1, 21.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 125, 3, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (70, 48, 3, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 17, 2, 51.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (58, 6, 1, 79.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (4, 98, 4, 82.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (91, 183, 2, 93.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 20, 1, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (80, 185, 1, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (23, 166, 1, 95.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (34, 75, 2, 21.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (62, 108, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (88, 198, 4, 21.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (99, 2, 4, 62.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (36, 102, 3, 39.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (33, 247, 4, 62.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (56, 88, 3, 95.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 129, 3, 71.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (73, 243, 4, 70.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (55, 206, 4, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (84, 176, 1, 37.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 37, 4, 47.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 45, 2, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (92, 95, 4, 57.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 40, 2, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 220, 1, 105.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (22, 12, 4, 69.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (92, 163, 2, 95.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (46, 114, 4, 53.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 69, 1, 86.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (87, 15, 2, 45.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (28, 241, 1, 51.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 31, 4, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 134, 3, 17.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (89, 210, 4, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (20, 159, 2, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 107, 2, 45.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 222, 3, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 248, 3, 23.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 227, 2, 94.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (31, 167, 4, 28.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (3, 189, 3, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (71, 82, 4, 104.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (62, 151, 1, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 134, 2, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (84, 144, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 236, 1, 112.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (65, 119, 3, 40.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (22, 150, 2, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 223, 3, 45.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (88, 45, 4, 54.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (59, 76, 2, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (16, 210, 1, 30.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 207, 4, 54.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 25, 2, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (56, 61, 2, 97.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (90, 105, 2, 47.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 31, 1, 42.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (45, 166, 4, 69.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (24, 127, 2, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (56, 27, 3, 58.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 19, 3, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 178, 2, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 242, 3, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (43, 152, 3, 53.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (39, 238, 2, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 84, 3, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (78, 100, 2, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (69, 87, 4, 34.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (89, 97, 4, 85.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (28, 52, 1, 70.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (34, 148, 2, 104.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (48, 222, 4, 69.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (100, 159, 4, 39.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (69, 23, 2, 35.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 76, 1, 21.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 9, 4, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 80, 4, 30.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (1, 1, 3, 22.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (3, 92, 2, 22.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (60, 31, 4, 34.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (92, 210, 4, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (17, 235, 3, 55.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (75, 148, 2, 71.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (46, 33, 4, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 102, 1, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (6, 217, 4, 26.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (3, 73, 3, 26.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (30, 122, 2, 67.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (82, 208, 2, 15.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 9, 1, 46.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (12, 116, 2, 47.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (89, 95, 2, 32.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (30, 110, 4, 64.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 220, 2, 92.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (47, 228, 1, 113.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 99, 4, 77.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (34, 234, 1, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 183, 4, 42.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (37, 236, 2, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (9, 123, 2, 78.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 63, 2, 50.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (65, 93, 2, 18.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (25, 102, 1, 112.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (81, 236, 4, 54.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 56, 3, 53.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (50, 35, 2, 111.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (77, 196, 2, 103.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (78, 159, 3, 22.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (60, 47, 4, 28.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 178, 3, 105.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (55, 123, 2, 60.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 143, 2, 16.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (2, 144, 3, 95.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (20, 39, 3, 65.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (80, 13, 4, 64.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (89, 74, 2, 54.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 155, 1, 90.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (57, 9, 3, 83.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (33, 199, 2, 90.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 124, 4, 97.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (61, 55, 2, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (37, 214, 4, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (99, 8, 3, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 185, 3, 99.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (23, 121, 1, 69.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (70, 126, 4, 64.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (24, 19, 3, 20.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 175, 3, 20.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (76, 137, 2, 43.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (64, 8, 2, 80.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (41, 12, 1, 25.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (82, 10, 1, 73.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 160, 2, 47.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 165, 1, 19.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (29, 77, 4, 87.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (54, 92, 3, 15.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (36, 180, 3, 78.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (49, 55, 2, 114.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (40, 209, 3, 44.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (79, 86, 3, 89.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (35, 1, 2, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (74, 48, 4, 65.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (63, 19, 4, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (71, 114, 1, 94.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (32, 21, 2, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (38, 19, 2, 97.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (5, 189, 3, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 190, 1, 78.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (21, 246, 4, 108.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (66, 14, 4, 49.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (5, 220, 2, 76.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (56, 104, 4, 100.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (14, 121, 3, 52.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (85, 52, 2, 39.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (97, 77, 2, 89.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (44, 243, 3, 104.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (78, 13, 3, 72.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 38, 4, 24.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (26, 183, 1, 53.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (5, 155, 3, 27.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 219, 3, 22.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (39, 239, 1, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (62, 171, 3, 63.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 54, 4, 66.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (98, 250, 4, 61.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (6, 166, 2, 17.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (31, 20, 1, 28.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (75, 152, 3, 33.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (95, 176, 1, 32.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (23, 11, 4, 77.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (68, 173, 1, 50.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (43, 126, 1, 83.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (75, 176, 3, 74.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (5, 74, 4, 21.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (88, 71, 1, 113.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (71, 50, 2, 38.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (19, 244, 4, 79.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (37, 13, 2, 105.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (8, 16, 3, 88.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 77, 1, 77.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (93, 11, 3, 53.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (7, 230, 4, 107.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (67, 169, 2, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (27, 116, 2, 78.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (67, 198, 2, 91.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (39, 143, 4, 48.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (58, 44, 1, 40.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (74, 195, 4, 75.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (99, 59, 4, 106.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (10, 212, 2, 68.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (86, 24, 4, 62.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (20, 247, 1, 32.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (84, 140, 4, 56.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (18, 243, 2, 27.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (42, 80, 2, 103.99);
insert into room (hotel_id, room_no, no_of_beds, price_per_night) values (46, 219, 1, 89.99);
